// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RelayEnv from "./constants/RelayEnv.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.mjs";

function $$default(props) {
  var pageProps = props.pageProps;
  return React.createElement(RescriptRelay.Context.Provider.make, {
              environment: RelayEnv.environment,
              children: React.createElement(props.Component, pageProps)
            });
}

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
